### ISSUE TITLE
API Gateway configure compatibility for both HTTP and HTTPS

### ISSUE THREAD

**Issue by tinafangkunding** [serverless-components/tencent-apigateway#2]
## Problems:

In the [fullstack template](https://github.com/serverless/components/tree/master/templates/tencent-fullstack-vue-application), we could use express and website components to make a serverless app. API Gateway could support HTTP or HTTPS, and if users want their API to support both HTTP and HTTPS, they have to configure like this in `serverless.yml`:
```
api:
  component: '@serverless/tencent-express'
 inputs:
    region: ap-beijing
    code: ./api
    functionName: fullstack-api
    role: execute-scf
    functionConf:
      timeout: 30
      memorySize: 512
    apigatewayConf:
      protocol: http&https   # configure of protocol support 
```
then, when they deploy like this, after `sls --debug` deployment, we'll find the API could be visit by HTTP and HTTPS, while in the static page, it can't be recognized :
```
  frontend: 
    url: https://hsrrivj-kugobji-xxxx.cos-website.ap-beijing.myqcloud.com
    env: 
      apiUrl: http&https://service-nifeq8x7-xxxxx.bj.apigw.tencentcs.com/release/
  api: 
    region:              ap-beijing
    functionName:        fullstack-api-pg
    apiGatewayServiceId: service-nifeq8x7
    url:                 http&https://service-nifeq8x7-xxxx.bj.apigw.tencentcs.com/release/
```
the request url became like this: (api url will be reffered in env)
```
Request URL: https://hsrrivj-kugobji-xxx.cos-website.ap-beijing.myqcloud.com/http&https://service-nifeq8x7-xxxxx.bj.apigw.tencentcs.com/release/user
```
and it will return a 404 error.

**Comment by pmuens** [comment]
Hey @tinafangkunding thanks for opening :+1:

I'd follow your suggestion and make `https` the default protocol. If users want to get more specific we could add support for a protocol list like this:

```yaml
api:
  component: '@serverless/tencent-express'
 inputs:
    region: ap-beijing
    code: ./api
    functionName: fullstack-api
    role: execute-scf
    functionConf:
      timeout: 30
      memorySize: 512
    apigatewayConf:
      protocols:
        - http
        - https
```

When we display the information about the deployment we could print a dedicated URL for each protocol so that users can just copy-and-paste the URL into their browsers:

```
frontend: 
    url: https://hsrrivj-kugobji-xxxx.cos-website.ap-beijing.myqcloud.com
    env: 
      apiUrl: https://service-nifeq8x7-xxxxx.bj.apigw.tencentcs.com/release/ # <-- here we try to find a `https` URL and otherwise default to `http`
  api: 
    region:              ap-beijing
    functionName:        fullstack-api-pg
    apiGatewayServiceId: service-nifeq8x7
    url: # <-- the following is a list of all the available URLs (given the protocols we've configured)
      https: https://service-nifeq8x7-xxxx.bj.apigw.tencentcs.com/release/
      http: http://service-nifeq8x7-xxxx.bj.apigw.tencentcs.com/release/
```

@tinafangkunding my main question is whether we need to support both: `http` and `https`. What's the use-case for `http` given that nowadays sites using that protocol are actively "exposed" as insecure by browsers and (according to rumors) downgraded in SEO.

Is there a user need to use `http` endpoints?
